package com.example.vaadin_jpa;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Table;
import com.example.vaadin_jpa.DOMAIN.Myentity;
import com.example.vaadin_jpa.DOMAIN.Дтп;
import com.vaadin.addon.jpacontainer.JPAContainer;
import com.vaadin.addon.jpacontainer.JPAContainerFactory;


public class dictonary extends CustomComponent {
	public static final String PERSISTENCE_UNIT = "dyf";
//    private JPAContainer<Myentity> persons;
    private JPAContainer<Дтп> persons;

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Table table_1;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public dictonary() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// table_1
        persons = JPAContainerFactory.make(Дтп.class,
//                persons = JPAContainerFactory.make(Myentity.class,
        		dictonary.PERSISTENCE_UNIT);
//        persons.addNestedContainerProperty("Районы.район");
        persons.addNestedContainerProperty("r.район");
        persons.addNestedContainerProperty("s.фио");
        
		table_1 = new Table(null,persons);
		
		table_1.setVisibleColumns(new Object[]{"дата","время","номерСертификата","место","r.район","s.фио","комментарий"});
		table_1.setColumnHeaders(new String[]{ "дата","время","номерСертификата","место","район","коммисар","комментарий"});
		
		table_1.setImmediate(false);
		table_1.setWidth("100.0%");
		table_1.setHeight("-1px");
		mainLayout.addComponent(table_1, "top:60.0px;left:20.0px;");
		
		return mainLayout;
	}

}
